### ISSUE TITLE
For the Image Super-Resolution task, how should the Houston dataset be divided into training and testing parts？

### ISSUE THREAD

**Issue by GuochaoCS** [WHU-Sigma/HyperSIGMA#12]

**Comment by Jamie-Adams369** [comment]
Same question!

**Comment by leonmakise** [comment]
We offer scripts to process the data:
[https://huggingface.co/datasets/WHU-Sigma/HyperSIGMA_Datasets/tree/main/HyperSIGMA_super-resolution](url).
 
You can also refer to [https://github.com/junjun-jiang/SSPSR/tree/master/mcodes](url).
