### ISSUE TITLE
For checkpoints 

### ISSUE THREAD

**Issue by Jamie-Adams369** [WHU-Sigma/HyperSIGMA#13]
Could you please upload the checkpoints of the ImageDenoising task?

![image](https://github.com/user-attachments/assets/8e8fb21e-ba8f-4a2c-8d44-dd50d4836244)

**Comment by leonmakise** [comment]
Hey Jamie,

We have updated them in HuggingFace. Plz have a try.

You can refer to the following link:
[https://huggingface.co/WHU-Sigma/HyperSIGMA/tree/main/Denoising_models](url)

**Comment by Jamie-Adams369** [comment]
Thanks a lot.
