### ISSUE TITLE
For MultispectralCD dataset

### ISSUE THREAD

**Issue by Jamie-Adams369** [WHU-Sigma/HyperSIGMA#14]
Thank you for your excellent job!

It seems that you have performed special processing on the OSCD dataset. 
1. When I was running the code, the 'ms_data. npy' files was missing from the training set path.
2.The label data seems to be in another folder.

![image](https://github.com/user-attachments/assets/107ab26a-9c7c-4840-912c-0ece1d0d01c2)
![image](https://github.com/user-attachments/assets/9a6bbbc0-8824-4875-80bb-f9acb3044fce)

Look forward to your reply！

**Comment by ChenHongruixuan** [comment]
Hi @Jamie-Adams369 ,

Thank you for your interest to our work! ms_data.npy is the multispectral data with 13 bands. Since each band is a separate file in the original OSCD dataset, we have combined them into a matrix of HxWx13 for convenience. You can generate it yourself. 

Best,
