### ISSUE TITLE
dataset about HyperSIGMA_denoising

### ISSUE THREAD

**Issue by nuistZPZ** [WHU-Sigma/HyperSIGMA#16]
我从huggingface中下载了HyperSIGMA_denoising，请问我应该如何正确打开它？
https://huggingface.co/datasets/WHU-Sigma/HyperSIGMA_Datasets/resolve/main/HyperSIGMA_denoising/Training/wdc.db/data.mdb

我使用微软的Access，提示“不可识别的数据库格式”。
我使用Python的pyodbc，报错如下
('HY000', '[HY000] [Microsoft][ODBC Microsoft Access Driver] 不能打开数据库“(未知)”。应用程序可能无法识别该数据库，或文件可能损坏。 (-1028) (SQLDriverConnect); [HY000] [Microsoft][ODBC Microsoft Access Driver] 不能打开数据库“(未知)”。应用程序可能无法识别该数据库，或文件可能损坏。 (-1028)')

**Comment by leonmakise** [comment]
You shall follow our codes to read .db files. Plz refer to [https://github.com/MyuLi/SST](url).

To view those images, you can just download the WDC dataset from the original source.

Just like #10.
