### ISSUE TITLE
TypeError: spat_vit_b_rvsa() got an unexpected keyword argument 'args'

### ISSUE THREAD

**Issue by kowo1001** [WHU-Sigma/HyperSIGMA#5]
Hello, I have two questions.

(1) I entered the command below, but I don't know why the error below occurs.
**$ bash train_complex.sh 1e-4 hypersigma 2 l2 100**

====================Command Result Start======================
Namespace(prefix='hypersigma_gaussian', arch='hypersigma', batchSize=4, lr=0.0001, wd=0, loss='l2', testdir=None, sigma=None, **training_dataset_path='./dataset/WDC/training/wdc.db',** pretrain='/mnt/code/users/yuchunmiao/hypersigma-master/pre_train/checkpoint-400.pth', init='kn', no_cuda=False, from_scratch=False, pretrain_path='./pre_train/spat-vit-base-ultra-checkpoint-1599.pth', no_log=False, threads=1, seed=2018, resume=False, no_ropt=False, chop=False, resumePath=None, dataroot='/data/HSI_Data/ICVL64_31.db', clip=1000000.0, gpu_ids=[0], basedir='./output/original_hypersigma_1e-4_spat-vit-base-ultra-checkpoint-1599_batch4_warmup_l2_epoch_100_gaussian_new_fusion', epoch=100, update_lr=5e-05, meta_lr=5e-05, n_way=1, k_spt=2, k_qry=5, task_num=16, update_step=5, update_step_test=10)
Cuda Acess: 1
=> creating model 'hypersigma'
load our vit fusion_new_v5 final models
Traceback (most recent call last):
  File "/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/hsi_denoising_gaussian_wdc.py", line 22, in <module>
    engine = Engine(opt)
  File "/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/hsi_setup.py", line 146, in __init__
    self.__setup()
  File "/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/hsi_setup.py", line 173, in __setup
    self.net = hypersigma(args=self.opt)
**TypeError: spat_vit_b_rvsa() got an unexpected keyword argument 'args'**
====================Command Result End======================

Any help is highly appreciated ;)

Thanks!

and, (2) I made the Washington dc mall.tif file( dc.tif )  into a train_0.mat, train_1.mat file through utility/mat_data.py in Image Denoising. Then I'm trying to make a train dataset. How can I make two mat files into a wdc.db file?

Or is there any other way to create a wbc.db file in **training_dataset_path**?

Please, suggest me how to do this.

**Comment by kowo1001** [comment]
When I took the recently updated source code and ran it again, the following error occurred.
I don't know why the error below occurs.

Any help is highly appreciated :D 

Thank U  :D 

**(venv) jwjang@gpusystem:~/project/hsi_foundation/HyperSIGMA/ImageDenoising$ bash train_complex.sh 1e-4 hypersigma 2 l2 100**


====================Command Result Start======================
mkdir: cannot create directory ‘./output/original_hypersigma_1e-4_spat-vit-base-ultra-checkpoint-1599_batch4_warmup_l2_epoch_100_complex_s3_8point’: File exists
Namespace(prefix='hypersigma_gaussian', arch='hypersigma', batchSize=4, lr=0.0001, wd=0, loss='l2', testdir=None, sigma=None, training_dataset_path='./dataset/WDC/training/wdc.db', pretrain='/mnt/code/users/yuchunmiao/hypersigma-master/pre_train/checkpoint-400.pth', init='kn', no_cuda=False, from_scratch=False, pretrain_path='./pre_train/spat-vit-base-ultra-checkpoint-1599.pth', no_log=False, threads=1, seed=2018, resume=False, no_ropt=False, chop=False, resumePath=None, dataroot='/data/HSI_Data/ICVL64_31.db', clip=1000000.0, gpu_ids=[0], basedir='./output/original_hypersigma_1e-4_spat-vit-base-ultra-checkpoint-1599_batch4_warmup_l2_epoch_100_complex_s3_8point', epoch=100, update_lr=5e-05, meta_lr=5e-05, n_way=1, k_spt=2, k_qry=5, task_num=16, update_step=5, update_step_test=10)
Cuda Acess: 1
=> creating model 'hypersigma'
load our vit fusion_new_v5 final models
Traceback (most recent call last):
File "/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/hsi_denoising_complex_wdc.py", line 23, in <module>
engine = Engine(opt)
File "/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/hsi_setup.py", line 146, in init
self.__setup()
File "/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/hsi_setup.py", line 173, in __setup
[self.net](http://self.net/) = hypersigma(args=self.opt)
File "/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/models/hypersigma/model.py", line 142, in spat_vit_b_rvsa
model = SSFusionFramework(
File "/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/models/hypersigma/model.py", line 97, in init
self.spat_encoder.init_weights('/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/pre_train/spat-vit-base-ultra-checkpoint-1599.pth')
File "/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/models/hypersigma/Spatial.py", line 495, in init_weights
checkpoint = torch.load(pretrained, map_location='cpu')
File "/data/jwjang/project/hsi_project/denoising/HSDT/pythonenv/venv/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "/data/jwjang/project/hsi_project/denoising/HSDT/pythonenv/venv/lib/python3.10/site-packages/torch/serialization.py", line 1262, in _legacy_load
magic_number = pickle_module.load(f, **pickle_load_args)
**_pickle.UnpicklingError: invalid load key, '\xff'.**
====================Command Result End======================

**Comment by leonmakise** [comment]
It seems to be error about the loaded pretrain model. May I know ur env details, especially torch version? :D

**Comment by aledamo** [comment]
I have the same issue when loading the pre-trained models, @leonmakise.
#4

**Comment by leonmakise** [comment]
@kowo1001 @aledamo Got it. Seem to be problems with the models we uploaded to huggingface. Let our team do a quick check. Some other models have similar error logs like this. Plz stay tune on it and give us some time. Thanks~

**Comment by leonmakise** [comment]
We found files are inconsistent with SHA256 check. A new model has been uploaded to huggingface. Please have a try and tell us if it is right now. https://huggingface.co/WHU-Sigma/HyperSIGMA/blob/main/spat-vit-base-ultra-checkpoint-1599.pth

**Comment by kowo1001** [comment]
> We found files are inconsistent with SHA256 check. A new model has been uploaded to huggingface. Please have a try and tell us if it is right now. https://huggingface.co/WHU-Sigma/HyperSIGMA/blob/main/spat-vit-base-ultra-checkpoint-1599.pth @kowo1001 @aledamo

I tried again and the same error occurred. Could you also change the **spec-vit-base-ultra-checkpoint-1599.pth** file and upload it back to the huggling face?

**Comment by leonmakise** [comment]
@kowo1001 Please check it now. https://huggingface.co/WHU-Sigma/HyperSIGMA/blob/main/spec-vit-base-ultra-checkpoint-1599.pth

**Comment by kowo1001** [comment]
(venv) jwjang@gpusystem:~/project/hsi_foundation/HyperSIGMA/ImageDenoising/utility$ python lmdb_data.py 
create wdc...
(926, 191, 64, 64)
map size (GB): 6.4770263671874995
/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/utility/WDC/wdc5.db
Traceback (most recent call last):
  File "/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/utility/lmdb_data.py", line 95, in <module>
    createDCmall()
  File "/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/utility/lmdb_data.py", line 85, in createDCmall
    create_lmdb_train(
  File "/data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/utility/lmdb_data.py", line 55, in create_lmdb_train
    env = lmdb.open(name+'.db', map_size=map_size, writemap=True)
lmdb.InvalidParameterError: /data/jwjang/project/hsi_foundation/HyperSIGMA/ImageDenoising/utility/WDC/wdc5.db: Invalid argument

> @kowo1001 Please check it now. https://huggingface.co/WHU-Sigma/HyperSIGMA/blob/main/spec-vit-base-ultra-checkpoint-1599.pth

Thank U 👍

**Comment by leonmakise** [comment]
Hi @kowo1001 , we understand your concerns and have uploaded the training and testing data for you now. You can find them in https://huggingface.co/datasets/WHU-Sigma/HyperSIGMA_Datasets/tree/main. Please have a try now.

**Comment by kowo1001** [comment]
> Hi @kowo1001 , we understand your concerns and have uploaded the training and testing data for you now. You can find them in https://huggingface.co/datasets/WHU-Sigma/HyperSIGMA_Datasets/tree/main/HyperSIGMA_denoising. Please have a try now.

Thank you for your kindness. I wonder how you made the training dataset and the test dataset. Could you explain it in detail or give me a link to refer to?  Thanks 👍👍 💯

**Comment by miaoyuchun** [comment]
Hi @kowo1001, we are unsure about the second question mentioned earlier. You can refer to the code released in [SST](https://github.com/MyuLi/SST), which our data processing pipeline fully follows.
